# Generated by Django 5.2.10 on 2026-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicyAcceptance',
        ),
    ]
