# Generated by Django 5.2.9 on 2026-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_teammembers_id_alter_userchatdb_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatdb',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='userproblems',
            old_name='content',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userchatdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userproblems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
