# Generated by Django 5.2.10 on 2026-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_userdashboard_owner'),
        ('app_1', '0002_delete_privacypolicyacceptance'),
    ]

    operations = [
    ]
