# Generated by Django 5.2.9 on 2026-01-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_rename_content_userchatdb_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatdb',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='userproblems',
            old_name='problem',
            new_name='content',
        ),
    ]
