# Generated by Django 5.2.11 on 2026-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_tharipistneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
