# Generated by Django 5.2.11 on 2026-02-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_remove_userpsycodata_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpsycodata',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamdatahistory',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpersonalitydata',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpsycodata',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='UserPsycoDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPersonalityDataHistoric',
        ),
    ]
